### ISSUE TITLE
Debug enabled, values rise

### ISSUE THREAD

**Issue by shaggy63** [slimstat/rh-trading-bot#1]
With trading and debug enabled I'm getting values like:
Buying power: $-1.0
-- 2021-01-30 14:24 ---------------------
            timestamp    DOGE  DOGE_SMA_F  DOGE_SMA_S   DOGE_RSI  DOGE_MACD  DOGE_MACD_S
718  2021-01-30 14:21   0.034    0.033458    0.033198  54.669138  -0.000072     0.000023
719  2021-01-30 14:22   0.034    0.033417    0.033219  54.669138  -0.000043     0.000014
720  2021-01-30 14:22  **64.000**    0.033375    0.033240  **99.994728**   2.703452     0.360473
721  2021-01-30 14:23  **14.000    2.698583**    **0.699573  55.608124   2.975441     0.709135**
722  2021-01-30 14:24  **26.000    3.280458**    **0.845073  59.964042   3.714416     1.109839**

**Comment by shaggy63** [comment]
It only happens with debug enabled.

Line 217 of bot.py

        for a_kraken_ticker, a_robinhood_ticker in config[ 'ticker_list' ].items():
            **if ( not config[ 'debug_enabled' ] ):**
                try:
                    result = get_json( 'https://api.kraken.com/0/public/Ticker?pair=' + str( a_kraken_ticker ) ).json()

                    if ( len( result[ 'error' ] ) == 0 ):
                        new_row[ a_robinhood_ticker ] = round( float( result[ 'result' ][ a_kraken_ticker ][ 'a' ][ 0 ] ), 3 )
                except:
                    print( 'An exception occurred retrieving prices.' )
                    self.is_trading_locked = True
                    return self.data
            else:
                new_row[ a_robinhood_ticker ] = round( float( randint( 10, 100 ) ), 3 )

It looks like if debug is enabled it doesn't get new values from kraken?

**Comment by slimstat** [comment]
Hi, I might need to rename that parameter. Enabling debug basically tells the bot to simulate all transactions. I use it when I don't need actual values from the APIs, but just something to make the code run. Also, make sure you always run the latest version, as the code is still evolving.

**Comment by slimstat** [comment]
Ok, I renamed the parameter and pushed a few code updates. I also cleaned up the mess in the main folder. Once you pull this latest commit, move your pickle files to the `pickle` folder before you restart the bot.
