### ISSUE TITLE
Data Snapshot Output

### ISSUE THREAD

**Issue by chrisjohnson1** [slimstat/rh-trading-bot#2]
It appears that the Data Snapshot Output resets at 755 back down to 717.  Additionally, the dataframe.pickle and orders.pickle never seems to grow.

**Comment by slimstat** [comment]
Hey @chrisjohnson1 could you pull the latest version? I fixed an issue happening when checking for gaps in the historical data. As for orders, that file grows when a new order is submitted (buy/sell).

**Comment by chrisjohnson1** [comment]
The latest code changes appear to have fixed the issue. Thank you, @slimstat.

**Comment by slimstat** [comment]
Great, thanks for testing my code! Hope you find it useful.
